POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667
Content-Type: application/json

{
  "entry": [
      {
        "date": "2015-01-02",
        "type": "OccupationalHealthcare",
        "specialist": "MD House",
        "diagnosisCodes": ["S62.5"],
        "description":
          "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
        "employerName": "UNI",
        "sickLeave": 
        {
          "startDate": "2019-01-09",
          "endDate": "2080-01-09"
        }
      }
      
    ]
}